# Generated by Django 4.1.7 on 2023-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='characters')),
                ('species', models.CharField(choices=[('HU', 'Humano'), ('SA', 'Saiyajin'), ('NA', 'Namekiano')], max_length=2)),
                ('gender', models.CharField(choices=[('FE', 'Woman'), ('MA', 'Man')], max_length=2)),
            ],
        ),
    ]
