# Generated by Django 4.1.7 on 2023-03-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('FE', 'Woman'), ('MA', 'Men')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/characters')),
                ('abilities', models.CharField(max_length=200)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='planet.planet')),
            ],
        ),
    ]
