# Generated by Django 4.1.7 on 2023-04-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='image',
        ),
    ]
