# Generated by Django 4.1.7 on 2023-03-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episode', '0001_initial'),
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episode.episode'),
        ),
    ]
