# Generated by Django 4.1.7 on 2023-03-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='air_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
